# Generated by Django 5.0.1 on 2024-02-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('ISBN', models.CharField(max_length=200)),
                ('PublishedDate', models.DateField()),
                ('Genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('DetailID', models.IntegerField(primary_key=True, serialize=False)),
                ('NumberofPages', models.IntegerField()),
                ('Publisher', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=100)),
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
