# Generated by Django 5.0.1 on 2024-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='DetailID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
