# Generated by Django 5.0.1 on 2024-02-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_bookid_alter_bookdetail_detailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='BookID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
