# Generated by Django 5.0.1 on 2024-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
